Do not call register_gbsim_controller() when gbsim is disabled
Previously, was getting the following error when --disable-gbsim was used.

gbridge/main.c:74: undefined reference to `register_gbsim_controller'
collect2: error: ld returned 1 exit status
Makefile:434: recipe for target 'gbridge' failed
make[1]: *** [gbridge] Error 1
make[1]: Leaving directory '/home/cfriedt/workspace/gbridge'
Makefile:308: recipe for target 'all' failed
make: *** [all] Error 2